// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_g6RC1h9AJjKMMnmU_81mRC4su5m8y4',
    appId: '1:850589793785:web:b3f9d5642056e973515128',
    messagingSenderId: '850589793785',
    projectId: 'olha-o-role-app',
    authDomain: 'olha-o-role-app.firebaseapp.com',
    storageBucket: 'olha-o-role-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYD1G12ynQu11UJqv8gOCFFzJomCU1bs',
    appId: '1:850589793785:android:33babaa448e9c5f6515128',
    messagingSenderId: '850589793785',
    projectId: 'olha-o-role-app',
    storageBucket: 'olha-o-role-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBag5JdJiz2GwRN_mXba_RSaNcG9v3sFck',
    appId: '1:850589793785:ios:6b3e9240ad9f4b11515128',
    messagingSenderId: '850589793785',
    projectId: 'olha-o-role-app',
    storageBucket: 'olha-o-role-app.firebasestorage.app',
    androidClientId: '850589793785-j8j3j8gfrjftm3jgne601mmk31uh11g7.apps.googleusercontent.com',
    iosClientId: '850589793785-u42mhpmt2j35jp0puqker9mujskdpkvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6_g6RC1h9AJjKMMnmU_81mRC4su5m8y4',
    appId: '1:850589793785:web:657e4aa8fa529810515128',
    messagingSenderId: '850589793785',
    projectId: 'olha-o-role-app',
    authDomain: 'olha-o-role-app.firebaseapp.com',
    storageBucket: 'olha-o-role-app.firebasestorage.app',
  );
}
